configfile: "config.json"
SRP=config['SRP']

import csv

with open('sample_data/SraRunTable.txt') as csvfile:
    reader = csv.DictReader(csvfile,delimiter='\t')
    SRR_runs = [row['Run'] for row in reader]

rule download_sra:
    output:
        expand("FASTQ/{id}_pass_1.fastq.gz",id=SRR_runs),
        expand("FASTQ/{id}_pass_2.fastq.gz",id=SRR_runs)
    conda:
        "envs/sra-tools.yaml"
    run:
        for id in SRR_runs:
            shell("fastq-dump --outdir FASTQ --gzip --skip-technical --readids --read-filter pass --dumpbase --split-3 --clip {id}")
